apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-slurm
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  tier: standard
  network: slurm
